version: "3.9"
services:
    mysql:
        image: mysql:latest
        container_name: psych_manager-db
        working_dir: /var/www/psych-manager
        volumes:
            - ./:/var/www/psych-manager
            - mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 0
        ports:
            - "33066:3306"
        restart: unless-stopped

    nginx:
        image: nginx:stable-alpine
        container_name: psych_manager-nginx
        working_dir: /var/www/psych-manager
        volumes:
            - ./:/var/www/psych-manager
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        depends_on:
            - php
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                DOCKER_USER_ID: ${DOCKER_USER_ID}
                DOCKER_GROUP_ID: ${DOCKER_GROUP_ID}
        container_name: psych_manager-php
        working_dir: /var/www/psych-manager
        volumes:
            - ./:/var/www/psych-manager
            - ./docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/docker-php-ext-overrides.ini
        depends_on:
            - mysql
        restart: unless-stopped

    node:
        build:
            context: .
            dockerfile: docker/node/Dockerfile
            args:
                DOCKER_USER_ID: ${DOCKER_USER_ID}
                DOCKER_GROUP_ID: ${DOCKER_GROUP_ID}
        container_name: psych_manager-node
        working_dir: /var/www/psych-manager
        volumes:
            - ./:/var/www/psych-manager
        restart: unless-stopped

networks:
    default:

volumes:
    mysql:
