export default {
    id: '',
    name: '',
    email: '',
    phone: '',
    gender: '',
    birthday_date: '',
    role: 0,
    connection_type_id: '',
    meeting_type_icon: '',
    connection_type_link: '',
    curator_contacts: '',
    connection_type_string: '',
    meeting_type: '',
    problem_id: '',
    category_id: '',
    problem_name: '',
    session_id: '',
    sessions: [],
    session_date_users: '',
    therapy: {
        concept_vision: '',
        plan: '',
        notes: '',
        problem_severity: '',
        request: '',
    }
}
